### ISSUE TITLE
Difficulties in Hardware interfacing

### ISSUE THREAD

**Issue by hassanismail92** [kumar-akshay324/robot-arm-control-ros#1]
Hello, I created the URDF, Launch Files and etc. of my robotic arm but I didn't connect my robotic arm with the ROS. I am cloning this [https://github.com/diestra-ai/xArm_Lewansoul_ROS.git](LewanSoul xarm) and I completed all the step mentioned in the [https://xarm-lewansoul-ros.readthedocs.io/en/latest/user_guide/1_1_introduction.html#run] (How to connect lewansoul robotic arm) but it is not interfacing with my robotic arm. The same error is coming which is mentioned in its readme. My device is connected in the Ubantuu and showing but i am confused that why it is not interfacing.

**Comment by kumar-akshay324** [comment]
I think you should raise this issue on their repo and share the details. Not sure how the problem is related to this repository.
